name: single-pscheduler-workflow

on:
  push:
    branches:
      - github-workflow
env:  
  BUILD_OS: u20

jobs:
  pscheduler-daemon:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          ref: 5.2.0

      # Fetch workflow script from projects
      - name: Fetch workflow script from projects
        env:
          github-token: ${{ secrets.GIT_ACTIONS }}
        run: |
          git clone https://github.com/cs1867/project.git project
          case "${{ env.BUILD_OS }}" in
            'ol8'|'el9')
              cp project/toolbox/workflows/github-el-workflow.sh .
              ;;
            'd11'|'d12'|'u20'|'u22'|'u24')
              cp project/toolbox/workflows/github-ub-workflow-skip-install.sh .
              ;;
          esac
      # Download artifacts
      - name: Download artifacts
        run: |
          mkdir -p artifacts
          echo "Downloading artifact for owamp"
          echo "Run ID: 12352717774"
          gh run download 12352717774 --repo cs1867/owamp -D artifacts/owamp --name "owamp-${{ env.BUILD_OS }}"  
          artifact_path="artifacts/owamp"
          echo "Listing artifact path:"
          ls -al "$artifact_path"
          echo "Downloading artifact for i2util"
          echo "Run ID: 12352680715"
          gh run download 12352680715 --repo cs1867/i2util -D artifacts/i2util --name "i2util-${{ env.BUILD_OS }}"  
          artifact_path="artifacts/perl-i2util"

        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}

      # Run docker oneshot builder and workflow script
      - name: Run Docker oneshot builder
        run: |
          case "${{ env.BUILD_OS }}" in
            'ol8'|'el9')
              curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - --run github-el-workflow.sh . '${{ env.BUILD_OS }}'
              ;;
            'd11'|'d12'|'u20'|'u22'|'u24')
              curl -s https://raw.githubusercontent.com/perfsonar/docker-oneshot-builder/main/build | sh -s - --run github-ub-workflow-skip-install.sh . '${{ env.BUILD_OS }}'
              ;;
          esac
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ env.BUILD_OS }}
          path: unibuild-repo
          retention-days: 5
