#
# Generate the testbed configuration
#

# TODO: Need to deal with pushes in multiple branches.

name: testbed

on:
  push:
    branches:
      # TODO: Remove this after development
      - 'issue-1410'
      - 'master'
      - 'main'
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/testbed.yml'
      - 'testbed/**/*'
      - 'pscheduler-test-*/testbed.json'
      - 'pscheduler-tool-*/testbed.json'
      - 'pscheduler-archiver-*/testbed.json'
      - 'pscheduler-context-*/testbed.json'

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build the testbed configuration
        run: |
          set -e
          make -C testbed
          cp testbed/testbed.json testbed/testbed-${{ github.ref_name }}.json

      - name: Publish the result
        uses: actions/upload-artifact@v4
        with:
          name: development-testbed
          path: testbed/testbed-${{ github.ref_name }}.json
          if-no-files-found: error
          overwrite: true
